DROP TABLE IF EXISTS USER;
CREATE TABLE USER(ID INT PRIMARY KEY, NAME VARCHAR(255) DEFAULT '');

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE(ID INT PRIMARY KEY, NAME VARCHAR(255) DEFAULT '');

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE(USER_ID INT, ROLE_ID INT, PRIMARY KEY(USER_ID, ROLE_ID));

-- 用户
INSERT INTO USER VALUES(1, 'user1');
INSERT INTO USER VALUES(2, 'user2');
-- 角色
INSERT INTO ROLE VALUES(1, 'role1');
INSERT INTO ROLE VALUES(2, 'role2');
-- 用户角色关联
INSERT INTO USER_ROLE VALUES(1, 1);
INSERT INTO USER_ROLE VALUES(1, 2);
INSERT INTO USER_ROLE VALUES(2, 1);
